### ISSUE TITLE
Log total time taken for a node to be terminated

### ISSUE THREAD

**Issue by shrinandj** [keikoproj/lifecycle-manager#17]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened**:
Lifecycle-manager prolongs the process of node termination but in return makes the shutdown graceful and removes the node from the LoadBalancer's target group. However, there is no easy way of identifying how long it took from the initiation of node termination to it being actually terminated.

**What you expected to happen**:
It will be good to log a message that shows the total time taken for the node to be drained, removed from target-group and actually being terminated.

**Comment by eytan-avisror** [comment]
Good idea, will look into this
