### ISSUE TITLE
structured v1.Event message for easy parsing

### ISSUE THREAD

**Issue by vigith** [keikoproj/lifecycle-manager#24]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature

It would be great if we can have the `message` in the `v1.Event` structured so we can parse it programatically. We are trying to do some data mining on these events so we can correlate the application behavior to the platform/infrastructure events.
eg, 
If we could format the below message 
```go
EventMessageLifecycleHookReceived = "lifecycle hook for event %v was received, instance %v will begin processing"
```
to 
```go
EventMessageLifecycleHookReceived = "eventID=%v; ec2ID=%v; details=lifecycle hook for the event was received, instance will begin processing
```
then we can easily parse the `key=value` pairs.

**Comment by eytan-avisror** [comment]
Will it make it more easily parsable if we make it a JSON object instead?
```
EventMessageLifecycleHookReceived = `{"eventID": "%v", "ec2ID": "%v", "message": "lifecycle hook for the event was received, instance will begin processing"}`

You could than marshal to a struct instead of parsing by delimiter `;`

**Comment by vigith** [comment]
Usually packing JSON inside JSON will introduce lot of escaping (`\"`), so users reading the message (eye balling) might frown https://play.golang.org/p/yoVhuuWyp_f

**Comment by eytan-avisror** [comment]
I was working on this feature a while back https://github.com/keikoproj/instance-manager/pull/36/files
I used this approach and pretty sure there was no escaping needed .. can you double check?

I was publishing the message this way:

```
message := fmt.Sprintf(`{"apiVersion":"v1alpha1","spotPrice":"%v", "useSpot": %t}`, price, useSpot)
```

**Comment by eytan-avisror** [comment]
`kubectl get events` will produce a clean result:
```
LAST SEEN   TYPE     REASON                    KIND      MESSAGE
2m59s       Normal   SpotRecommendationGiven             {"apiVersion":"v1alpha1","spotPrice":"0.0069", "useSpot": true}
```

When looking at json payload, you will see escaping e.g. `kubectl get events -o json`
```
...
"lastTimestamp": "2019-11-27T18:07:20Z",
            "message": "{\"apiVersion\":\"v1alpha1\",\"spotPrice\":\"0.0069\", \"useSpot\": true}",
            "metadata": {
...
```

But for programatic access to this, we can unmarshal without needing to do anything with the payload.

So I think JSON would work fine in this case.
