### ISSUE TITLE
Regarding Permission

### ISSUE THREAD

**Issue by janavenkat** [keikoproj/lifecycle-manager#45]
I don't have any issue but I have problem with setting up sqs and IAM role 

Done the setup but regarding permission https://github.com/keikoproj/lifecycle-manager#required-aws-auth as mentioned here where I have to apply in IAM role and sqs

**Comment by eytan-avisror** [comment]
Hi @janavenkat 

This depends on how you setup IAM for pods in your cluster, if you are using [KIAM](https://github.com/uswitch/kiam) then all you need to do is create the IAM role as mentioned in the docs and annotate the lifecycle-manager pod with `iam.amazonaws.com/role: <your role>`.
If you are using some other way for Pod / IAM auth you may have to implement differently.

Will close this for now, if you need additional help with this, feel free to join our [slack](https://keikoproj.slack.com/) org and reach out.

**Comment by janavenkat** [comment]
Hi, 
Thanks for your response but am not able to signup your slack

**Comment by eytan-avisror** [comment]
If you are not using KIAM/other solution to route IAM credential to pods, then you need to attach an IAM role on the node that is running the controller directly.
The recommendation is to use KIAM in general for achieving this with more flexibility/security.

Outside of the IAM roles described in AWS docs (which are used for notifications between SQS and ASG), you need an additional/separate IAM role to allow lifecycle-manager to do it's work (e.g. read from SQS, deregister targets, etc.),  https://github.com/keikoproj/lifecycle-manager#required-aws-auth describes the required permissions for this role.

Installation of this controller should be:
##### 1. AWS configuration (https://docs.aws.amazon.com/autoscaling/ec2/userguide/configuring-lifecycle-hook-notifications.html#sqs-notifications)
- Create Notification IAM role
- Create SQS queue
- Create lifecycle hook on ASG (assumes the notification role) and point to created SQS queue for `EC2_INSTANCE_TERMINATING`

Once this part is done, you have an autoscaling group, that posts an SQS message to a queue every time a termination is triggered.

##### 2. Kubernetes configuration (https://github.com/keikoproj/lifecycle-manager/blob/master/examples/lifecycle-manager.yaml)
- Create an IAM role to be used by the container, it should have the access described in https://github.com/keikoproj/lifecycle-manager#required-aws-auth
- Create required resources (namespace, deployment, service account, binding, etc)
- Make sure the pod has the permissions associated with the controller IAM role (as mentioned, you can use KIAM/other solution or simply attach this IAM role (or add the required permissions) directly to the EC2 instance that is running the controller.

Let me know if this helps, not sure why slack is not working for you, you should be able to join our org with a public slack account.

**Comment by janavenkat** [comment]
<img width="1395" alt="Screenshot 2020-02-13 at 09 24 08" src="https://user-images.githubusercontent.com/28565699/74414914-a322db00-4e42-11ea-828a-fcb157b4a71c.png">

Am getting error like this when am trying to join your slack workspace

**Comment by janavenkat** [comment]
Thanks for the detailed information it works well and one more question is it possible to disable `alb deregister`

**Comment by eytan-avisror** [comment]
Yes, you can pass flag `--with-deregister=false`, see here:
https://github.com/keikoproj/lifecycle-manager/blob/master/cmd/serve.go#L107

Are you not using `aws-alb-ingress-controller`? you will get 504s on scale-downs without it.
